### PR TITLE
Update highcharts to v4.1.10

### PR DESCRIPTION
**Pull request by jkhedani**
Sorry, I've never submitted a pull request before. Installed my fork as a custom package in my current meteor project utilizing high charts and the features I needed are working. Not sure what highcharts-more does but can confirm the no data module is working. Thanks for maintaining this!

### CODE REVIEW

**Comment by jhuenges** [comment]
You did the right thing, except it is better to use the non-minfied versions. Meteor will minify every js file. If you could change this, it would be great :+1:

**Comment by MaazAli** [comment]
Yeah, no minification please!

**Comment by jkhedani** [comment]
Ah, that makes sense. Updated and pushed. Thanks for the guidance!

**Comment by jhuenges** [comment]
I ll test this later today and merge if everything works

**Comment by jhuenges** [comment]
Looks good to me. @MaazAli should I merge this, or will you do this and publish it to atmosphere?

**Comment by MaazAli** [comment]
@jhuenges you can merge :+1:

**Pull request merged**
