### PR TITLE
Removed solid gauge

### PR DESCRIPTION
**Pull request by jhuenges**
Version bumped to 0.3.0

### CODE REVIEW

**Comment by MaazAli** [comment]
Any way to make it a smooth transition for users to migrate to the other packages after we remove this?

**Comment by jhuenges** [comment]
I guess only if we add the gauge package as a dependency. But then everybody would get it even if they dont need it

**Comment by jhuenges** [comment]
Maybe we can insert a js-file wich console.warn´s about the change.

**Comment by MaazAli** [comment]
Might be the way to go, do you want to just throw that in?

**Comment by jhuenges** [comment]
Yeah, I can do that

**Comment by jhuenges** [comment]
@MaazAli I hope that is enough :)

**Comment by MaazAli** [comment]
Looks good!

**Comment by jhuenges** [comment]
Great :) Now you only have to publish the other packages and everything is good to go!

**Pull request merged**
