### PR TITLE
Adding support for HighMaps + updating HighCharts to v4.2.5

### PR DESCRIPTION
**Pull request by rodriguesgm**
Adding support for HighMaps. To use need just to do
$('#container').highcharts('Map', options);

### CODE REVIEW

**Comment by MaazAli** [comment]
@jhuenges

**Comment by jhuenges** [comment]
Looks good, cant test it right now

**Comment by rodriguesgm** [comment]
Great man.

I did the tests with this example here
http://www.highcharts.com/maps/demo/rich-info.
I'm using a local pachage waiting your accept on the pull-request.

Thanks

**Comment by jhuenges** [comment]
@rodriguesgm Can you introduce HighMaps in the readme.md? Just add a section, a link to some examples and describe how to use this.

Thanks!

**Comment by rodriguesgm** [comment]
@jhuenges Done
Thanks

**Comment by jhuenges** [comment]
@MaazAli I would merge this, if you dont mind

**Pull request merged**
