### PR TITLE
Adding support for heatmaps

### PR DESCRIPTION
**Pull request by mhourahine**
Added support for HightChart Heatmaps.  I also bumped the version number.  Hope that works for you.

### CODE REVIEW

**Comment by jhuenges** [comment]
Looks good to me. Can you maybe add a short description in the readme? Or just mention that highmaps is also available

**Comment by mhourahine** [comment]
Ok did that.  I also noticed the version of the heatmap.js file I added wasn't inline with the highcharts version so I updated everything to the latest v4.1.3.

**Comment by jhuenges** [comment]
:+1:

**Comment by MaazAli** [comment]
Will test it out once I get home, good work.

**Comment by MaazAli** [comment]
I'm wondering if this package should support all these different highchart addons. Considering the users of this package do not have a way to opt-out of importing the heatmaps addon for example. This would cause all  of the additional javascript to be loaded when some users may not need it at all. Causing the initial .js payload to be even larger than it already is. What do you guys think?

**Comment by jhuenges** [comment]
We could create different packages. I already have a highstock package.

**Comment by mhourahine** [comment]
I'd be fine with that.  Maaz, if you update your package to have the latest
versions, I'll just create another package called highcharts-heatmaps that
will depend on yours and add the heatmap module.  Sound good?

**Comment by MaazAli** [comment]
@mhourahine Sounds great. That seems like the best approach to be honest. I'll update the package to the latest.

**Comment by MaazAli** [comment]
@mhourahine  here is the commit: https://github.com/MaazAli/Meteor-HighCharts/commit/9948139e995f5169d08ea212dd60a750aad54fba

**Comment by mhourahine** [comment]
Awesome thanks!  Here is the new highcharts-heatmaps repo:
https://github.com/mhourahine/meteor-highcharts-heatmaps

Mike

**Comment by MaazAli** [comment]
Looks good!

**Pull request closed without merging**
